name: "Neo Ighodaro"
jobTitle: "Head of Engineering"
employer: "PINKTUM"
baseUrl: "https://neoighodaro.com"
logoImage:
  url: "https://neoighodaro.com/assets/neo.jpg"
  width: 500
  height: 500
twitter: "@neoighodaro"
github: "neoighodaro"

# plausible.io analytics
plausible:
  # Default for enabled is: process.env.NODE_ENV === 'production', so turn off explicitly if you don't need it
  # enabled: true
  domain: "neoighodaro.com"

# Will be used in JSON ld for SEO
social:
  - "https://medium.com/@neo"
  - "https://github.com/neoighodaro"
  - "https://twitter.com/neoighodaro"

title: "Neo Ighodaro | Head of Engineering"
description: "Neo is a Head of Software Engineering based in Hamburg"
postsPageDescription: "Read writings from Neo, Head of Software Engineering based in Hamburg, Germany"

links:
  Posts: "/posts"

# HTML is supported
homepageHeadline: "Hi, I'm Neo üëãüèΩ"
homepageSubHeadline: "Head of Engineering &nbsp;‚Ä¢&nbsp;  Aspiring House Husband"

postsPerPage: 20
mediumLink: "https://medium.com/@neo"
mediumFollowersCount: "1.2K"
